{{- if .Values.rbac.enabled }}
{{- $roleName := default .Release.Name .Values.rbac.role.name }}
{{- $roleBindingName := default .Release.Name .Values.rbac.roleBinding.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName | quote }}
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleBindingName | quote }}
subjects:
- kind: ServiceAccount
  name: {{ default .Release.Name .Values.rbac.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $roleName | quote }}
{{- end }}
